#!/bin/sh

set -e

cd $AUTOPKGTEST_TMP

cat <<EOF >test_import.py
from PyQt5.QtCore import QFile
from PyQt5.QtDBus import QDBusConnection
from PyQt5.QtGui import QColor
from PyQt5.QtMultimedia import QAudio
from PyQt5.QtMultimediaWidgets import QGraphicsVideoItem
from PyQt5.QtNetwork import QLocalSocket
from PyQt5.QtPositioning import QGeoCoordinate
from PyQt5.QtQml import QQmlEngine
from PyQt5.QtQuick import QQuickView
from PyQt5.QtSensors import QSensor
from PyQt5.QtSerialPort import QSerialPortInfo
from PyQt5.QtSql import QSqlQuery
from PyQt5.QtSvg import QSvgRenderer
from PyQt5.QtWebChannel import QWebChannel
from PyQt5.QtWebKit import QWebSettings
from PyQt5.QtWebKitWidgets import QWebView
from PyQt5.QtWebSockets import QWebSocket
from PyQt5.QtWidgets import QWidget
from PyQt5.QtXmlPatterns import QXmlSchema
from PyQt5.QtX11Extras import QX11Info
from dbus.mainloop.pyqt5 import DBusQtMainLoop
EOF

for py in $(py3versions -s); do
  echo "testing $py"
  $py test_import.py
  echo "testing $py-dbg"
  $py-dbg test_import.py 2>&1
done
